### ISSUE TITLE
Feature: back to top button

### ISSUE THREAD

**Issue by vikasbhvsr** [wesbos/awesome-uses#426]
As the list grows, it's too long to scroll back up to top. I have already developed the code.

```js
const backToTop = document.querySelector('back-to-top')
window.onscroll = function () {
  scrollFunction()
}
backToTop.addEventListener('click', backToTopFunction)

function scrollFunction() {
  if (document.body.scrollTop > 20 || document.documentElement.scrollTop > 20) {
    backToTop.style.display = 'inline-block'
  } else {
    backToTop.style.display = 'none'
  }
}

function backToTopFunction() {
  document.body.scrollTop = 0
  document.documentElement.scrollTop = 0
}
```
```css
.backToTop {
    transform: rotate(90deg);
    position: fixed;
    bottom: 1%;
    right: 1%;
    background: var(--pink);
    font-size: 3rem;
    cursor: pointer;
    border-radius: 3px;
    padding: 1rem;
    transition: background-color 0.2s ease 0s;
    display: none;
}
```
```html
<div class="back-to-top">‹</div>
```
